/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plans */
        get: operations["list_plans_api_plans_get"];
        put?: never;
        /** Create Plan */
        post: operations["create_plan_api_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_api_plans__plan_id__get"];
        put?: never;
        post?: never;
        /** Delete Plan */
        delete: operations["delete_plan_api_plans__plan_id__delete"];
        options?: never;
        head?: never;
        /** Update Plan */
        patch: operations["update_plan_api_plans__plan_id__patch"];
        trace?: never;
    };
    "/api/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Records */
        get: operations["list_records_api_records_get"];
        put?: never;
        /** Create Record */
        post: operations["create_record_api_records_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/records/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Record */
        get: operations["get_record_api_records__record_id__get"];
        put?: never;
        post?: never;
        /** Delete Record */
        delete: operations["delete_record_api_records__record_id__delete"];
        options?: never;
        head?: never;
        /** Update Record */
        patch: operations["update_record_api_records__record_id__patch"];
        trace?: never;
    };
    "/api/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_stats_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Heatmap */
        get: operations["heatmap_api_stats_heatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backup/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Backup */
        post: operations["export_backup_api_backup_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backup/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Backup */
        post: operations["import_backup_api_backup_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** HeatmapDay */
        HeatmapDay: {
            /** Date */
            date: string;
            /** Completed Plans */
            completed_plans: number;
            /** Records Count */
            records_count: number;
        };
        /** PlanCreate */
        PlanCreate: {
            /** Date */
            date: string;
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "in_progress" | "done" | "cancelled";
            /**
             * Priority
             * @default medium
             * @enum {string}
             */
            priority: "high" | "medium" | "low";
            /**
             * Category
             * @default 默认
             */
            category: string;
        };
        /** PlanOut */
        PlanOut: {
            /** Date */
            date: string;
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "in_progress" | "done" | "cancelled";
            /**
             * Priority
             * @default medium
             * @enum {string}
             */
            priority: "high" | "medium" | "low";
            /**
             * Category
             * @default 默认
             */
            category: string;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PlanUpdate */
        PlanUpdate: {
            /** Date */
            date?: string | null;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Status */
            status?: ("pending" | "in_progress" | "done" | "cancelled") | null;
            /** Priority */
            priority?: ("high" | "medium" | "low") | null;
            /** Category */
            category?: string | null;
        };
        /** RecordCreate */
        RecordCreate: {
            /** Date */
            date: string;
            /** Title */
            title: string;
            /**
             * Content
             * @default
             */
            content: string;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /**
             * Is Completed
             * @default true
             */
            is_completed: boolean;
            /**
             * Category
             * @default 默认
             */
            category: string;
            /** Linked Plan Id */
            linked_plan_id?: number | null;
        };
        /** RecordOut */
        RecordOut: {
            /** Date */
            date: string;
            /** Title */
            title: string;
            /**
             * Content
             * @default
             */
            content: string;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /**
             * Is Completed
             * @default true
             */
            is_completed: boolean;
            /**
             * Category
             * @default 默认
             */
            category: string;
            /** Linked Plan Id */
            linked_plan_id?: number | null;
            /** Id */
            id: number;
            /** Done At */
            done_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RecordUpdate */
        RecordUpdate: {
            /** Date */
            date?: string | null;
            /** Title */
            title?: string | null;
            /** Content */
            content?: string | null;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /** Is Completed */
            is_completed?: boolean | null;
            /** Category */
            category?: string | null;
            /** Linked Plan Id */
            linked_plan_id?: number | null;
        };
        /** StatsDay */
        StatsDay: {
            /** Date */
            date: string;
            /** Total Plans */
            total_plans: number;
            /** Done Plans */
            done_plans: number;
            /** Planned Minutes */
            planned_minutes: number;
            /** Records Count */
            records_count: number;
            /** Recorded Minutes */
            recorded_minutes: number;
        };
        /** StatsOverview */
        StatsOverview: {
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Total Plans */
            total_plans: number;
            /** Done Plans */
            done_plans: number;
            /** Completion Rate */
            completion_rate: number;
            /** Planned Minutes */
            planned_minutes: number;
            /** Recorded Minutes */
            recorded_minutes: number;
            /** By Category */
            by_category: {
                [key: string]: number;
            };
            /** Days */
            days: components["schemas"]["StatsDay"][];
            /** Consecutive Recording Days */
            consecutive_recording_days: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    list_plans_api_plans_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                status?: string | null;
                category?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plan_api_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_plan_api_plans__plan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_plan_api_plans__plan_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_records_api_records_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                category?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_record_api_records_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_record_api_records__record_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_record_api_records__record_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_record_api_records__record_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_stats_overview_get: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heatmap_api_stats_heatmap_get: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeatmapDay"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_backup_api_backup_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    import_backup_api_backup_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
